apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels-helm-{{.Release.Name}}
  annotations:
    policies.kyverno.io/title: Require Labels
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod, Label
    policies.kyverno.io/description: >-
      Define and use labels that identify semantic attributes of your application or Deployment.
      A common set of labels allows tools to work collaboratively, describing objects in a common manner that
      all tools can understand. The recommended labels describe applications in a way that can be
      queried. This policy validates that the label `{{.Values.RequireLabels.key}}` is specified with some value.      
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: check-for-labels-helm
    {{- if hasKey .Values.RequireLabels "excludeNamespaces"}}
    exclude:
      resources:
        namespaces:
          {{- range .Values.RequireLabels.excludeNamespaces}}
          - {{. -}}
          {{end -}}
    {{end}}
    match:
      resources:
        {{- if hasKey .Values.RequireLabels "includeNamespaces"}}
        namespaces:
        {{- range .Values.RequireLabels.includeNamespaces}}
        - {{. -}}
        {{end -}}
        {{end}}
        kinds:
        {{- range .Values.RequireLabels.resources}}
        - {{. -}}
        {{end}}
    validate:
      message: "The label {{.Values.RequireLabels.key}} is required."
      pattern:
        metadata:
          labels:
            {{.Values.RequireLabels.key -}}: "?*"
