# Declare include & exclude namespace data that needs to be passed into your templates.


# includeNamespaces - If not specificed, by default the policy will be applied to all namespaces
# excludeNamespaces - This is important to make sure we don't kill sensitive infrastructure
RequireLabels:
  # includeNamespaces:
  #   - loki
  excludeNamespaces:
    - kube-system
    - kyverno
    - local-path-storage
    - ironman
    - vision
    - spider-man
    - captain-america
    - ant-man
    - hawk-eye
    - gswarm-critical
    - gswarm-lambda
  resources:
    - Pod
  key: podowner
